-- Seed practice_recommendations library (idempotent)
INSERT INTO practice_recommendations (
  skill, criterion, trigger_pattern, task_title, task_description, task_type,
  estimated_band_impact, estimated_sessions_to_resolve, estimated_minutes, task_href
) VALUES
  ('speaking', 'lexical_resource', 'repetitive_vocabulary', 'Vocabulary upgrade drill',
   'Rewrite 5 answers using synonyms for overused words (like, good, nice, thing). Record one minute on each topic: hometown, hobbies, food, work/study, travel.',
   'drill', 0.50, 2, 12, '/dashboard/student/vocabulary'),
  ('speaking', 'fluency_coherence', 'filler_word_overuse', 'Filler-free fluency drill',
   'Speak for 90 seconds on one familiar topic without um/uh/like/you know. Pause silently instead of filling.',
   'targeted_speaking_session', 0.50, 2, 10, '/dashboard/ielts/student/speaking?mode=practice'),
  ('speaking', 'grammatical_range_accuracy', 'past_tense_inconsistency', 'Past tense control drill',
   'Tell a story about a past holiday using only past simple and past continuous correctly.',
   'drill', 0.50, 2, 10, '/dashboard/ielts/student/grammar?focus=tense'),
  ('speaking', 'grammatical_range_accuracy', 'run_on_sentences', 'Sentence control speaking drill',
   'Answer 4 Part 1 questions with exactly 2–3 clear sentences each.',
   'targeted_speaking_session', 0.50, 2, 12, '/dashboard/ielts/student/speaking?mode=practice'),
  ('speaking', 'fluency_coherence', 'weak_coherence_markers', 'Linking words in speech',
   'Practise answers using because, however, for example, and as a result to connect ideas.',
   'lesson', 0.25, 2, 10, '/dashboard/ielts/student/grammar?focus=linking'),
  ('speaking', 'lexical_resource', 'redundant_intensifiers', 'Drop the empty intensifiers',
   'Replace very/really/so + basic adjective with one precise word. Drill 8 upgrades aloud.',
   'drill', 0.25, 1, 8, '/dashboard/student/vocabulary'),
  ('speaking', 'pronunciation', 'word_stress_error', 'Word stress practice',
   'Pick 10 topic words. Mark stressed syllables, say each 5 times, then use in a sentence.',
   'drill', 0.25, 3, 10, '/dashboard/ielts/student/speaking?mode=practice'),
  ('writing', 'lexical_resource', 'repetitive_vocabulary', 'Writing vocabulary upgrade',
   'Write 5 sentences on the same essay topic using no repeated content words.',
   'drill', 0.50, 2, 15, '/dashboard/student/vocabulary'),
  ('writing', 'grammatical_range_accuracy', 'run_on_sentences', 'Complex sentence control prompt',
   'Write one Task 2 paragraph using 3 complex sentences and zero comma splices.',
   'targeted_writing_prompt', 0.50, 2, 20, '/dashboard/ielts/student/writing?tab=task2&focus=sentence-control'),
  ('writing', 'grammatical_range_accuracy', 'past_tense_inconsistency', 'Tense consistency writing drill',
   'Write 120 words recounting a chart trend. Highlight every verb and check tense.',
   'drill', 0.50, 2, 15, '/dashboard/ielts/student/grammar?focus=tense'),
  ('writing', 'coherence_cohesion', 'weak_coherence_markers', 'Paragraph linking drill',
   'Write two body paragraphs with topic sentences plus linking phrases.',
   'lesson', 0.50, 2, 15, '/dashboard/ielts/student/grammar?focus=linking'),
  ('writing', 'coherence_cohesion', 'poor_paragraph_linking', 'Cohesion & flow rewrite',
   'Add 3 cohesive ties (this, these, such) so ideas flow without jumps.',
   'targeted_writing_prompt', 0.50, 2, 18, '/dashboard/ielts/student/writing?tab=task2&focus=cohesion'),
  ('writing', 'lexical_resource', 'redundant_intensifiers', 'Cut redundant intensifiers',
   'Edit one paragraph: remove every very/really/extremely unless essential.',
   'drill', 0.25, 1, 10, '/dashboard/ielts/student/writing?tab=task2'),
  ('writing', 'task_response', 'weak_task_response', 'Clear position statement drill',
   'Write 3 Task 2 introductions with a clear position in sentence 2.',
   'targeted_writing_prompt', 0.50, 2, 20, '/dashboard/ielts/student/writing?tab=task2&focus=position'),
  ('writing', 'task_achievement', 'weak_task_achievement', 'Task 1 overview accuracy drill',
   'Describe one chart: overview in sentence 1, then 2 detail paragraphs with accurate figures.',
   'targeted_writing_prompt', 0.50, 2, 25, '/dashboard/ielts/student/writing?tab=task1&focus=overview')
ON CONFLICT (skill, criterion, trigger_pattern) DO UPDATE SET
  task_title = EXCLUDED.task_title,
  task_description = EXCLUDED.task_description,
  task_type = EXCLUDED.task_type,
  estimated_band_impact = EXCLUDED.estimated_band_impact,
  estimated_sessions_to_resolve = EXCLUDED.estimated_sessions_to_resolve,
  estimated_minutes = EXCLUDED.estimated_minutes,
  task_href = EXCLUDED.task_href;
