import type { Question } from "../types";

const GRAMMAR_ITEMS: Omit<Question, "id" | "section">[] = [
  {
    band: 4.0,
    type: "fill_blank",
    question: "By 2030, renewable energy ___ (account) for 50% of production.",
    correct: "will account",
    explanation: "Future with will + base verb for predictions.",
    saudiTrap: "Using present simple for future time marker 'By 2030'.",
    topic: "environment",
  },
  {
    band: 4.0,
    type: "error_correction",
    question: "Correct: She don't like online classes.",
    correct: "She doesn't like online classes.",
    explanation: "Third person singular: doesn't + base verb.",
    saudiTrap: "Arabic has no auxiliary do/does in present negative.",
    topic: "education",
  },
  {
    band: 4.5,
    type: "mcq",
    question: "The report ___ published last year.",
    options: ["was", "were", "is", "has"],
    correct: "was",
    explanation: "Passive past: was + past participle.",
    topic: "technology",
  },
  {
    band: 4.5,
    type: "fill_blank",
    question: "If governments invest more, pollution ___ (decrease).",
    correct: "will decrease",
    explanation: "First conditional: if + present, will + base.",
    topic: "environment",
  },
  {
    band: 5.0,
    type: "error_correction",
    question: "Correct: The students which study abroad gain experience.",
    correct: "The students who study abroad gain experience.",
    explanation: "Defining relative clause for people: who not which.",
    topic: "education",
  },
  {
    band: 5.0,
    type: "mcq",
    question: "Choose the article: ___ Vision 2030 framework is ambitious.",
    options: ["The", "A", "An", "(no article)"],
    correct: "The",
    explanation: "Unique/definite framework → the.",
    saudiTrap: "Article omission before unique proper-noun frameworks.",
    topic: "Vision2030",
  },
  {
    band: 5.5,
    type: "fill_blank",
    question: "Not only the economy but also society ___ (be) affected.",
    correct: "is",
    explanation: "Not only... but also → verb agrees with nearest subject (society).",
    topic: "urbanization",
  },
  {
    band: 5.5,
    type: "error_correction",
    question: "Correct: He go to hospital every week.",
    correct: "He goes to the hospital every week.",
    explanation: "Third person goes; article with institution when specific.",
    saudiTrap: "Missing article the before hospital.",
    topic: "health",
  },
  {
    band: 6.0,
    type: "mcq",
    question: "Had the policy been enforced, emissions ___ lower.",
    options: [
      "would have been",
      "will be",
      "would be",
      "have been",
    ],
    correct: "would have been",
    explanation: "Third conditional past hypothetical.",
    topic: "environment",
  },
  {
    band: 6.0,
    type: "fill_blank",
    question: "The data ___ (collect) from 120 schools last term.",
    correct: "were collected",
    explanation: "Passive past plural: data were collected (treat as plural).",
    topic: "education",
  },
  {
    band: 6.5,
    type: "error_correction",
    question: "Correct: The manager suggested to hire more nurses.",
    correct: "The manager suggested hiring more nurses.",
    explanation: "Suggest + gerund, not to-infinitive.",
    topic: "health",
  },
  {
    band: 6.5,
    type: "mcq",
    question: "Rarely ___ such rapid urban growth.",
    options: ["have we seen", "we have seen", "we see", "did we saw"],
    correct: "have we seen",
    explanation: "Negative inversion: Rarely + auxiliary + subject + verb.",
    topic: "urbanization",
  },
  {
    band: 7.0,
    type: "fill_blank",
    question: "It is technology that ___ (enable) remote diagnosis.",
    correct: "enables",
    explanation: "Cleft sentence: It is X that + verb agrees with X.",
    topic: "technology",
  },
  {
    band: 7.0,
    type: "error_correction",
    question: "Correct: The number of patients have increased.",
    correct: "The number of patients has increased.",
    explanation: "The number of + singular verb has.",
    topic: "health",
  },
  {
    band: 7.5,
    type: "mcq",
    question: "Choose nominalization: The committee decided to review the plan.",
    options: [
      "The committee made a decision to review the plan",
      "The committee decided review the plan",
      "The committee deciding the plan",
      "The committee decide review",
    ],
    correct: "The committee made a decision to review the plan",
    explanation: "Nominalization: decision instead of decided.",
    topic: "education",
  },
  {
    band: 7.5,
    type: "fill_blank",
    question: "Were it not for scholarships, many students ___ (not attend) university.",
    correct: "would not attend",
    explanation: "Formal conditional inversion: Were it not for...",
    topic: "education",
  },
  {
    band: 8.0,
    type: "error_correction",
    question: "Correct: Neither the CEO nor the directors was present.",
    correct: "Neither the CEO nor the directors were present.",
    explanation: "Neither nor → verb agrees with nearer plural subject.",
    topic: "technology",
  },
  {
    band: 8.0,
    type: "mcq",
    question: "So compelling ___ the evidence that the board approved funding.",
    options: ["was", "were", "is", "has been"],
    correct: "was",
    explanation: "So + adjective + inversion was the evidence.",
    topic: "environment",
  },
];

const MORE_GRAMMAR: Omit<Question, "id" | "section">[] = [
  {
    band: 4.0,
    type: "mcq",
    question: "There ___ many clinics in the district.",
    options: ["are", "is", "was", "be"],
    correct: "are",
    explanation: "There are + plural noun.",
    topic: "health",
  },
  {
    band: 4.5,
    type: "fill_blank",
    question: "She ___ (work) in Jeddah since 2019.",
    correct: "has worked",
    explanation: "Since + present perfect.",
    topic: "urbanization",
  },
  {
    band: 5.0,
    type: "mcq",
    question: "The lecture, ___ was broadcast online, attracted thousands.",
    options: ["which", "who", "whom", "whose"],
    correct: "which",
    explanation: "Non-defining relative for things: which.",
    topic: "technology",
  },
  {
    band: 5.5,
    type: "error_correction",
    question: "Correct: If I would have time, I would travel.",
    correct: "If I had time, I would travel.",
    explanation: "Second conditional: if + past, would + base.",
    saudiTrap: "Using would in if-clause.",
    topic: "education",
  },
  {
    band: 6.0,
    type: "fill_blank",
    question: "The new campus is ___ (expect) to open next year.",
    correct: "expected",
    explanation: "Passive: is expected to.",
    topic: "Vision2030",
  },
  {
    band: 6.5,
    type: "mcq",
    question: "Hardly ___ the results published when debate began.",
    options: ["had", "have", "has", "was"],
    correct: "had",
    explanation: "Hardly had + past participle (inversion).",
    topic: "education",
  },
  {
    band: 7.0,
    type: "error_correction",
    question: "Correct: Each of the programmes are accredited.",
    correct: "Each of the programmes is accredited.",
    explanation: "Each of + plural noun → singular verb is.",
    topic: "education",
  },
  {
    band: 7.5,
    type: "fill_blank",
    question: "What is needed is greater ___ (invest) in research.",
    correct: "investment",
    explanation: "Nominalization: investment not invest.",
    topic: "technology",
  },
  {
    band: 8.0,
    type: "mcq",
    question: "No sooner ___ the policy announced than reactions emerged.",
    options: ["had", "has", "was", "did"],
    correct: "had",
    explanation: "No sooner had + past participle.",
    topic: "environment",
  },
];

export function buildGrammarQuestions(): Question[] {
  const base = [...GRAMMAR_ITEMS, ...MORE_GRAMMAR].map((item, i) => ({
    ...item,
    id: `grammar-${item.band}-${String(i + 1).padStart(2, "0")}`,
    section: "grammar" as const,
  }));

  const pads: Question[] = [];
  const bands = [4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0] as const;
  const topics = [
    "education",
    "technology",
    "environment",
    "health",
    "urbanization",
    "Vision2030",
  ];
  while (base.length + pads.length < 40) {
    const n = base.length + pads.length + 1;
    const band = bands[n % bands.length];
    const topic = topics[n % topics.length];
    pads.push({
      id: `grammar-pad-${n}`,
      section: "grammar",
      band,
      type: n % 2 === 0 ? "fill_blank" : "error_correction",
      question: `Passive rewrite (${topic}): Officials ___ the policy last month.`,
      correct: "implemented the policy",
      explanation: "Past active → Officials implemented the policy.",
      saudiTrap: "Avoiding passive when formal tone required.",
      topic,
    });
  }
  return [...base, ...pads].slice(0, 40);
}
