const vm = require("vm");
const fs = require("fs");
const path = require("path");

function genSilenceMs(ms) {
  const ctx = { Int16Array, Int8Array, Float32Array, console };
  const lamePath = path.join(__dirname, "../node_modules/lamejs/lame.all.js");
  vm.runInNewContext(fs.readFileSync(lamePath, "utf8"), ctx);
  const enc = new ctx.lamejs.Mp3Encoder(1, 24000, 128);
  const samples = new Int16Array(Math.floor((24000 * ms) / 1000));
  const parts = [];
  for (let i = 0; i < samples.length; i += 1152) {
    const buf = enc.encodeBuffer(samples.subarray(i, i + 1152));
    if (buf.length) parts.push(Buffer.from(buf));
  }
  const flush = enc.flush();
  if (flush.length) parts.push(Buffer.from(flush));
  return Buffer.concat(parts);
}

const b500 = genSilenceMs(500);
const b1000 = genSilenceMs(1000);

const outPath = path.join(__dirname, "../lib/mp3SilenceBuffers.js");
const content = `/** Pre-encoded mono 24kHz MP3 silence (generated by scripts/genMp3Silence.cjs) */
export const SILENCE_500_MS_B64 = "${b500.toString("base64")}";
export const SILENCE_1000_MS_B64 = "${b1000.toString("base64")}";
`;

fs.writeFileSync(outPath, content);
console.log("Wrote", outPath, "500ms:", b500.length, "1000ms:", b1000.length);
